name: Test workflow                    # Workflow 이름
on:                                  # Event 감지
  push:
    branches:
      - develop
jobs:                                # Job 설정
   build:
      name: CI
      runs-on: self-hosted
      defaults:
          run:
              working-directory: ../..
      steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          
      - name: Stop old server (ignore error)
        run: |
            killall -9 node || true
            
      - name: build
        run: |
            cd test-chatUniv
            git pull origin develop
            yarn install
            yarn run build 

          
   deploy:
      needs: build
      name: CD
      runs-on: self-hosted
      defaults:
          run:
              working-directory: ../..
      steps:    
      - name : run new server
        env:
            RUNNER_TRACKING_ID: ""
        run : |
            cd test-chatUniv
            nohup serve -n -s  build & 
