name: Test workflow                    # Workflow 이름
on:                                  # Event 감지
  push:
    branches:
      - develop                 
jobs:                                # Job 설정
  deploy:
        name: CD
        runs-on: self-hosted

        steps:
        - name: Get Github Actions IP
          id: ip
          uses: haythem/public-ip@v1.2

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-2

        - name: Add Github Actions IP to Security group
          run: |
            aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
  
        - name: SSH Commands
          run: |
              echo "$AWS_SSH_KEY" > ssh_key.pem
              chmod 600 ssh_key.pem
              ssh -i ssh_key.pem ubuntu@${{ secrets.AWS_SSH_HOST }}
              script: |
                cd git/test-chatUniv
                yarn install
                yarn start
  
        - name: Remove Github Actions IP From Security Group
          run: |
            aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32








        
