name: Test workflow                    # Workflow 이름
on:                                  # Event 감지
  push:
    branches:
      - develop
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: docker image build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{secrets.IMAGE_NAME}}:${secrets.IMAGE_TAG} .

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: docker image container remove
        run :  sudo docker rm `docker ps -a -q`
               sudo docker rmi $(sudo docker images -q)
          
      - name: docker image build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{secrets.IMAGE_NAME}}:${secrets.IMAGE_TAG} .

      - name: push image to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.IMAGE_NAME}}:${secrets.IMAGE_TAG}
        
        
  deploy:
        needs: CI
        name: CD
        runs-on: self-hosted
        defaults:
          run:
              working-directory: ../..
              
        steps:
        - name: docker stop container
          run: |
            sudo docker stop $(sudo docker ps -aq) || true
        - name: pull image from docker hub
          run: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{secrets.IMAGE_NAME}}:${secrets.IMAGE_TAG}
        - name: docker run
          run: |
            docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/${{secrets.IMAGE_NAME}}:${secrets.IMAGE_TAG}
            
            

            
  
  








        
